---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu/xenial64  # 16.04
  - name: ubuntu/trusty64  # 14.04
  - name: centos/7         # 7
  - name: debian/stretch64 # 9
  - name: debian/jessie64  # 8

suites:
  - name: latest
    run_list:
      - recipe[cop_composer::default]
    attributes:
      composer:
        auth:
          http-basic:
            repo.magento.com:
              user: '123'
              pass: '456'
          github-oauth:
            github.com: '789'

  - name: specified
    run_list:
      - recipe[cop_composer::default]
    attributes:
      composer:
        install:
          version: '1.3.2'
          checksum: 'c99af08d16b7833e50cc14629e0555a153d451b6'
        auth:
          http-basic:
            repo.magento.com:
              user: '123'
              pass: '456'
          github-oauth:
            github.com: '789'
